# Generated by Django 6.0.6 on 2026-06-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Original filename or user-provided title.', max_length=500)),
                ('file', models.FileField(help_text='The uploaded PDF file.', upload_to='documents/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current processing status.', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, default='', help_text='Celery task ID for status polling.', max_length=255)),
                ('pages_count', models.PositiveIntegerField(default=0)),
                ('chunks_count', models.PositiveIntegerField(default=0)),
                ('nodes_extracted', models.PositiveIntegerField(default=0)),
                ('relationships_extracted', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title of the disruption event.', max_length=500, unique=True)),
                ('event_type', models.CharField(help_text="Category of disruption (e.g. 'port_closure', 'sanctions').", max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('informational', 'Informational')], default='medium', help_text='Estimated impact severity.', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the disruption event.')),
                ('locations', models.JSONField(blank=True, default=list, help_text='Affected geographic locations.')),
                ('materials', models.JSONField(blank=True, default=list, help_text='Affected materials/products/commodities.')),
                ('affected_entities', models.JSONField(blank=True, default=list, help_text='Names of affected companies/organizations.')),
                ('source_url', models.URLField(blank=True, default='', help_text='URL of the source news article.', max_length=1000)),
                ('source_name', models.CharField(blank=True, default='', help_text='Name of the news source.', max_length=200)),
                ('event_date', models.DateTimeField(blank=True, help_text='When the event occurred or was reported.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this event is still considered active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
